### ISSUE TITLE
Timezone not correct or missing when using JSON output format

### ISSUE THREAD

**Issue by michaelgierer3** [pictuga/morss#57]
Hi guys!

**I have noticed that the time-zone information in JSON output is missing.**

_RSS/XML output:_
`<published>2021-04-19T16:30:00+02:00</published>`

_JSON output:_
`"time":"2021-04-19T16:30:00Z",`

So, the **+2:00** is missing! 

![image](https://user-images.githubusercontent.com/49281469/115426631-f8097080-a200-11eb-8ab8-2ec4ead3302e.png)

Doesn't matter whether you use the Browser or the CLI version ...

**Comment by pictuga** [comment]
Well spotted, thanks! I found the source of the problem. https://git.pictuga.com/pictuga/morss/src/commit/6880a443e0a376a45191eeda20e52bb792f1e80d/morss/feeds.py#L519 I'll fix it in the coming days (or weeks)

**Comment by pictuga** [comment]
Should be fixed in 3a1d5649927ffe33f98cc2aa1c598a9cce9b62bb (not yet live at https://morss.it/ ). Do you confirm it's now working on your side? (json will convert to UTC as it does not support time zones, but at least the time will be the right one)

**Comment by michaelgierer3** [comment]
Hi!

I am sorry to tell you that the situation remains the same - the timezone in JSON format is still wrong (should be - 2 hours, then 'Z'/UTC would be correct):

![image](https://user-images.githubusercontent.com/49281469/115865688-f6c28880-a438-11eb-9568-6d1f7109fa6e.png)


Thanks for investigating and let me know when you have changed the code again.

Kind Regards,
Michael

**Comment by is181041** [comment]
Hi!

I have the same problem.

Kind Regards,
Manuel

**Comment by pictuga** [comment]
what about now? (f9d7794bcca38ebfa9b04042ab9259efb694a377)

**Comment by michaelgierer3** [comment]
Hello,

I can now confirm that the JSON timezone information is correct.
Thank you for the fast implementation.

![image](https://user-images.githubusercontent.com/49281469/115990858-d83dc800-a5c5-11eb-86af-45298484e7c1.png)


Kind Regards,
Michael
